# helm install opentwinsv2-dgraph dgraph/dgraph -f kubernetes/dgraph/values.yaml

zero:
  service:
    type: NodePort
    nodePort: 32008

alpha:
  acl:
    enabled: false
  encryption:
    enabled: false
  configFile:
    config.yaml: |
      security:
        whitelist: 10.0.0.0/8,172.0.0.0/8,192.168.0.0/16
  service:
    type: NodePort
    nodePort: 32009
  persistentVolume:
    enabled: true

ratel:
  enabled: true
  service:
    type: NodePort
    nodePort: 32010