apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: no-tracing
spec:
  tracing:
    samplingRate: "0"
  nameResolution:
    component: "consul"
    version: "v1"
    configuration:
      selfRegister: true
  mtls:
    enabled: false