# helm install opentwinsv2-redis oci://registry-1.docker.io/bitnamicharts/redis -f .\kubernetes\redis\values.yaml

auth:
  enabled: false

master:
  service:
    type: NodePort
    nodePorts:
      redis: "47342"
  resources:
    limits: 
      memory: "1Gi"
    requests: 
      memory: "512Mi"
replica:
  resources:
    limits: 
      memory: "1Gi"
    requests: 
      memory: "512Mi"